name: Vite React Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout code
    - name: Checkout repository
      uses: actions/checkout@v4

    # Step 2: Setup Node.js
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20' # Use your Node.js version

    # Step 3: Install dependencies
    - name: Install dependencies
      run: npm install

    # Step 4: Build the project
    - name: Build Vite project
      run: npm run build

    # Step 5 (Optional): Upload build output as artifact
    - name: Upload dist folder
      uses: actions/upload-artifact@v4
      with:
        name: vite-dist
        path: dist